// packages/vue/src/quiz/QuizQuestion.vue
<template>
  <form @submit.prevent="handleSubmit">
    <p class="question">
      <span>{{ question.num1 }}</span>
      <span>{{ question.operation }}</span>
      <span>{{ question.num2 }}</span>
      <span>=</span>
      <input
        type="number"
        placeholder="???"
        v-model="userAnswer"
        ref="inputRef"
        @input="handleInput"
      />
    </p>
  </form>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'

import { type Question, calculateAnswer } from './quiz.controller'

const props = defineProps<{
	question: Question
}>()

const emit = defineEmits<(e: 'answer', isCorrect: boolean) => void>()

const userAnswer = ref('')
const inputRef = ref<HTMLInputElement | null>(null)

const handleSubmit = () => {
	if (userAnswer.value === '') return

	const isCorrect =
		Number.parseInt(userAnswer.value) === calculateAnswer(props.question)
	emit('answer', isCorrect)
	userAnswer.value = ''
	inputRef.value?.focus()
}

const handleInput = (event: Event) => {
	const target = event.target as HTMLInputElement
	userAnswer.value = target.value
}

onMounted(() => {
	inputRef.value?.focus()
})
</script>

<style scoped>
.question {
  align-items: baseline;
	display: inline flex;
	font-size: var(--font-size-8);
	font-weight: var(--font-weight-8);
	gap: var(--size-3);

	input {
		background: none;
		inline-size: 4ch;
	}

	::-webkit-inner-spin-button {
		display: none;
	}
}
</style>

// packages/svelte/src/quiz/QuizQuestion.svelte
<script lang="ts">
import type { Question } from './quiz.controller'
import { calculateAnswer } from './quiz.controller'

export let question: Question
export let onAnswer: (isCorrect: boolean) => void

let userAnswer = ''
let inputRef: HTMLInputElement

function handleSubmit(event: Event) {
	event.preventDefault()

	if (userAnswer === '') return

	const isCorrect = Number.parseInt(userAnswer) === calculateAnswer(question)

	onAnswer(isCorrect)
	userAnswer = ''
	inputRef.focus()
}
</script>

<form on:submit={handleSubmit}>
	<p class="question">
		<span>{question.num1}</span>
		<span>{question.operation}</span>
		<span>{question.num2}</span>
		<span>=</span>
		<!-- svelte-ignore a11y_autofocus -->
		<input
			type="number"
			placeholder="???"
			autofocus
			bind:this={inputRef}
			bind:value={userAnswer}
		/>
	</p>
</form>

<style>
	.question {
		align-items: baseline;
		display: inline flex;
		font-size: var(--font-size-8);
		font-weight: var(--font-weight-8);
		gap: var(--size-3);

		input {
			background: none;
			inline-size: 4ch;
		}

		::-webkit-inner-spin-button {
			display: none;
		}
	}
</style>
