// packages/angular/src/app/quiz/quiz-progress.component.ts
import { CommonModule } from '@angular/common'
import { Component, Input } from '@angular/core'

import type { Question } from './quiz.service'

@Component({
	selector: 'app-quiz-progress',
	imports: [CommonModule],
	template: `
    <p class="result" aria-label="Correct answers of all answers">
      {{ correctAnswers }} of {{ questions.length }}
    </p>
  `,
	styles: [
		`
			.result {
				display: grid;
				gap: var(--size-8);
				justify-items: center;
			}
		`,
	],
})
export class QuizProgressComponent {
	@Input() questions: Question[] = []

	get correctAnswers() {
		return this.questions.filter((q) => q.isCorrect).length
	}
}

// packages/vue/src/quiz/QuizProgress.vue
<template>
  <p class="result" aria-label="Correct answers of all answers">
    {{ correctAnswers }} of {{ questions.length }}
  </p>
</template>

<script setup lang="ts">
import { computed } from 'vue'

import type { Question } from './quiz.controller'

const props = defineProps<{
	questions: Question[]
}>()

const correctAnswers = computed(
	() => props.questions.filter((q) => q.isCorrect).length,
)
</script>

<style scoped>
.result {
  display: grid;
	gap: var(--size-8);
	justify-items: center;
}

</style>
